# Generated by Django 4.1.7 on 2023-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=8)),
                ('image', models.ImageField(upload_to='images/')),
                ('statut', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('hdr', models.BooleanField()),
                ('phd', models.BooleanField()),
            ],
        ),
    ]
