# Generated by Django 4.1.7 on 2023-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urpimaApp', '0003_auteur_livre_projetderecherche_these_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chercheur',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
