# Generated by Django 4.1.7 on 2023-02-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urpimaApp', '0004_chercheur_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='design_de_couverture',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='disponibilité',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='numéro_de_classification',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='table_des_matieres',
        ),
        migrations.AddField(
            model_name='livre',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
