# Generated by Django 4.1.7 on 2023-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urpimaApp', '0005_remove_livre_design_de_couverture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledejournal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articledejournal',
            name='pages',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='articledejournal',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articledejournal',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articledejournal',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articledejournal',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
