# Generated by Django 4.1.7 on 2023-02-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urpimaApp', '0006_articledejournal_date_articledejournal_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledejournal',
            name='informations_financement',
        ),
    ]
