# Generated by Django 4.1.7 on 2023-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urpimaApp', '0007_remove_articledejournal_informations_financement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetderecherche',
            name='biblio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='hypotheses',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='implications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='methodologie',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='objectifs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='plan_de_travail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='questions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='resultats_attendus',
            field=models.TextField(null=True),
        ),
    ]
