# Generated by Django 4.1.7 on 2023-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urpimaApp', '0008_alter_projetderecherche_biblio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetderecherche',
            name='biblio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='hypotheses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='implications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='methodologie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='objectifs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='plan_de_travail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='resultats_attendus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
